### ISSUE TITLE
unable to fetch all objects

### ISSUE THREAD

**Issue by sunnymatharuuk** [gavignon/sfdc-generate-data-dictionary#1]
Firstly, great tool.

I've just found this as I was looking for a data dictionary generator.

It looks to be working fine, but it is only giving me the dictionary for 3 sObjects whereas the org has far more. The user i tried to export this with, has got access to everything, so i don't think it is a permissions issue. Any thoughts?

**Comment by gavignon** [comment]
Hi @sunnymatharuuk

Thanks for your feedback !
Unfortunately I can't reproduce the issue, I just added the feature to display simple debug messages that may help me to investigate.

Could you please execute the updated version of the tool (**[1.0.3](https://www.npmjs.com/package/sfdc-generate-data-dictionary)**) with the **debug** option (--debug true from command-line and 'debug':true as a module) and paste the content of the debug file here (inside _node_modules/sfdc-generate-data-dictionary/files_ directory) ?
What are the expected sObjects VS actual sObjects ?

If I need more information to help you on this issue I will update the tool to display much more information.

Thanks

**Comment by sunnymatharuuk** [comment]
Thanks for the speedy reply.

I've updated to v1.0.3, but am having trouble locating the debug file.

Here is my terminal input/output:

```
sunnymatharuuk/data-dictionary » sgd -u MYUSERNAME -p MYPASSWORD -o . -l https://test.salesforce.com -c true --debug true --deleteFolders false
Connected as MYUSERNAME
Downloading...
176.56kB downloaded
Generating...
Saving PROJECT_Data_Dictionary_2017-11-16.xlsx...
PROJECT_Data_Dictionary_2017-11-16.xlsx successfully saved!
sunnymatharuuk/data-dictionary » sgd --version
1.0.3
```

I added `--debug true` but I couldn't see a log file created anywhere on my Mac.

I then added  `--deleteFolders false`, in case the file was being removed, but still no joy finding the file.

Does the log file go somewhere else?

**Comment by sunnymatharuuk** [comment]
ok found the debug.log file.

Maybe a note to add in the readme that this stuff ends up in the application install directories rather than the place where I run the command from.

mine were in `/usr/local/lib/node_modules/sfdc-generate-data-dictionary`

Anyway, here's the output:

*11162017_debug.log*:
```
[09:38:50] Connected as smatharu@blah.com
[09:38:52] ["Account","Contact","PB_Property_Partner__c"]
[09:39:36] Connected as smatharu@blah.com
[09:39:38] ["Account","Contact","PB_Property_Partner__c"]
[09:41:09] Connected as smatharu@blah.com
[09:41:18] ["Account","Contact","PB_Property_Partner__c"]
[09:42:12] Connected as smatharu@blah.com
[09:42:13] ["Account","Contact","PB_Property_Partner__c"]
[09:48:51] Connected as smatharu@blah.com
[09:48:53] ["Account","Contact","PB_Property_Partner__c"]
```

In addition, the `metadata` and `describe` folders also have 3 JSON files each, corresponding to the objects above.

Maybe it's failing for some reason on the 4th object (of approx 30), and then stopping at that point?

If it's important, the 3rd object you're seeing there, is a managed package object. Just mentioning it in case something to do with the managed namespace is throwing your app off.

**Comment by sunnymatharuuk** [comment]
A little more. I've installed jsforce locally and executed the `globalDescribe()` call from the command line.

It lists a bunch of objects (some that are true sobjects, as well as share objects, tooling api objects etc), and then th ebottom of the output says `... 330 more items ] }`

Is there a chance that the output is too large? I'd be surprised as the managed package is big but not enormous, but you never know.

**Comment by gavignon** [comment]
Thanks

I will add the note in the Readme about how to found the debug files.

I actually use the describeGlobal() function from jsforce, could you please paste the ouput here or send it to me to help us to debug ?

**Comment by sunnymatharuuk** [comment]
Figured it out.

You've got this line:
`if (object.custom && (object.name.indexOf('__c') !== -1) && (object.name.split('__').length - 1 < 2))`

..after you do the globalDescribe call. You're explicitly excluding managed package objects.

if I change it to this:
`if (object.custom && (object.name.indexOf('__c') !== -1))`
...then it works fine.

Maybe you can add a switch to include/exclude managed package objects?

Better yet have the switch, but have it also be configurable if there are only certain managed namespaces I want to include/exclude.

**Comment by gavignon** [comment]
Oh Yes, you're right I forgot that I excluded managed package objects...
I will add the feature to have it configurable asap, thanks !

**Comment by sunnymatharuuk** [comment]
retested.

This condition doesn't evaluate properly on my machine:
`if(config.excludeManagedPackage){`

I had to change it to the following to get it to work:
`if(config.excludeManagedPackage == 'true'){`
