### ISSUE TITLE
Unable to generate extract file for Lucidchart

### ISSUE THREAD

**Issue by rangaraj** [gavignon/sfdc-generate-data-dictionary#5]
I tried to generate an extract that I want to import into Lucidchart.
According to the help doc here... it should be possible using the -lc switch...

sgd -u "Username" -p "Passwd" -l "https://test.salesforce.com" --sobjects "Account,Contact,Opportunity,OpportunityLineItem,Lead,Quote__c,SBQQ__QuoteLine__c,Product2,Pricebook2,PricebookEntry" -lc true -o \GIT\OUT

However, I only get the Excel file containing the data dictionary for the objects selected.

Is this feature working? Please respond asap.

tia

**Comment by gavignon** [comment]
Hello @rangaraj 
Thanks for reporting the issue and sorry for the late answer.

Please update to the latest version, you should be able to do it properly now!

**Comment by gavignon** [comment]
Fixed in **1.2.14**
